"""Create export_links table for T-087 signed file links.

Revision ID: 20260613_0053
Revises: 20260613_0052
Create Date: 2026-06-13 00:00:00.000000

T-087: Signed file links and expiry management.
Stores secure, temporary download links for shared exports.
Each link has a signed token and expiry time for permission-checked downloads.
"""

import sqlalchemy as sa

from alembic import op

revision = "20260613_0053"
down_revision = "20260613_0052"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("share_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(256), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False,
            server_default=sa.func.now()
        ),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["share_id"], ["export_shares.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_export_links_token"),
    )
    op.create_index(
        op.f("ix_export_links_share_id"),
        "export_links",
        ["share_id"],
        unique=False
    )
    op.create_index(
        op.f("ix_export_links_token"),
        "export_links",
        ["token"],
        unique=True
    )
    op.create_index(
        op.f("ix_export_links_expires_at"),
        "export_links",
        ["expires_at"],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_export_links_expires_at"),
        table_name="export_links"
    )
    op.drop_index(
        op.f("ix_export_links_token"),
        table_name="export_links"
    )
    op.drop_index(
        op.f("ix_export_links_share_id"),
        table_name="export_links"
    )
    op.drop_table("export_links")
    # ### end Alembic commands ###
