"""Add optimization metadata and fitted_model_id to recommendations

Revision ID: ad8caf696011
Revises: 20260624_0066
Create Date: 2026-06-25 15:23:05.670171
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad8caf696011'
down_revision = '20260624_0066'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopify_refunds_connector_id', table_name='shopify_refunds')
    op.drop_index('ix_shopify_refunds_order_id', table_name='shopify_refunds')
    op.drop_index('ix_shopify_refunds_refund_created_at', table_name='shopify_refunds')
    op.drop_index('ix_shopify_refunds_tenant_id', table_name='shopify_refunds')
    op.drop_table('shopify_refunds')
    op.drop_index('ix_klaviyo_campaigns_sent_at', table_name='klaviyo_campaigns')
    op.drop_index('ix_klaviyo_campaigns_tenant_id', table_name='klaviyo_campaigns')
    op.drop_table('klaviyo_campaigns')
    op.drop_index('ix_acquisition_cohorts_cohort_dates', table_name='acquisition_cohorts')
    op.drop_index('ix_acquisition_cohorts_tenant', table_name='acquisition_cohorts')
    op.drop_constraint('acquisition_cohorts_tenant_id_fkey', 'acquisition_cohorts', type_='foreignkey')
    op.create_foreign_key(None, 'acquisition_cohorts', 'tenants', ['tenant_id'], ['id'])
    op.drop_index('ix_alert_ack_tenant_alert', table_name='alert_acknowledgements')
    op.drop_index('ix_alert_ack_tenant_user', table_name='alert_acknowledgements')
    op.drop_index('ix_alert_dismiss_tenant_alert', table_name='alert_dismissals')
    op.drop_index('ix_alert_dismiss_tenant_user', table_name='alert_dismissals')
    op.drop_index('ix_alert_event_log_tenant_alert', table_name='alert_event_log')
    op.drop_index('ix_alert_event_log_tenant_created', table_name='alert_event_log')
    op.drop_index('ix_alert_recipients_tenant_id', table_name='alert_recipients')
    op.drop_index('ix_alert_recipients_user_id', table_name='alert_recipients')
    op.drop_index('ix_alert_thresholds_tenant_id', table_name='alert_thresholds')
    op.drop_index('ix_analysis_view_shares_saved_view_id', table_name='analysis_view_shares')
    op.drop_index('ix_analysis_view_shares_shared_by_id', table_name='analysis_view_shares')
    op.drop_index('ix_analysis_view_shares_tenant_id', table_name='analysis_view_shares')
    op.drop_index('ix_annotations_created_by_id', table_name='annotations')
    op.drop_index('ix_annotations_event_date', table_name='annotations')
    op.drop_index('ix_annotations_saved_view_id', table_name='annotations')
    op.drop_index('ix_annotations_tenant_id', table_name='annotations')
    op.alter_column('cohort_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cohort_snapshots', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cohort_snapshots_cohort_dates', table_name='cohort_snapshots')
    op.drop_index('ix_cohort_snapshots_tenant', table_name='cohort_snapshots')
    op.drop_index('ix_cohort_snapshots_window', table_name='cohort_snapshots')
    op.drop_index('ix_cost_input_versions_cost_input_id', table_name='cost_input_versions')
    op.drop_index('ix_cost_inputs_tenant_type', table_name='cost_inputs')
    op.drop_index('ix_custom_segments_tenant_id', table_name='custom_segments')
    op.drop_index('ix_email_delivery_log_tenant_status', table_name='email_delivery_log')
    op.drop_index('ix_escalation_rule_tenant_type', table_name='escalation_rules')
    op.drop_index('ix_export_links_token', table_name='export_links')
    op.drop_index('ix_inventory_risk_snapshots_tenant_date', table_name='inventory_risk_snapshots')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_operational_impact_snapshots_tenant_date', table_name='operational_impact_snapshots')
    op.add_column('recommendations', sa.Column('optimization_metadata', sa.JSON(), nullable=True, comment='Optimization run details: expected_conversions, lift_pct, model accuracy'))
    op.add_column('recommendations', sa.Column('fitted_model_id', sa.Uuid(), nullable=True, comment='FK to the fitted model that generated this recommendation'))
    op.create_foreign_key(None, 'recommendations', 'fitted_models', ['fitted_model_id'], ['id'])
    op.alter_column('roles', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('ix_saved_analysis_views_created_by_id', table_name='saved_analysis_views')
    op.drop_index('ix_saved_analysis_views_tenant_id', table_name='saved_analysis_views')
    op.drop_index('ix_shopify_order_line_items_tenant_sku_date', table_name='shopify_order_line_items')
    op.alter_column('simulations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('tenant_memberships', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_memberships', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('simulations', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('ix_shopify_order_line_items_tenant_sku_date', 'shopify_order_line_items', ['tenant_id', 'sku', 'order_created_at'], unique=False)
    op.create_index('ix_saved_analysis_views_tenant_id', 'saved_analysis_views', ['tenant_id'], unique=False)
    op.create_index('ix_saved_analysis_views_created_by_id', 'saved_analysis_views', ['created_by_id'], unique=False)
    op.alter_column('roles', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'fitted_model_id')
    op.drop_column('recommendations', 'optimization_metadata')
    op.create_index('ix_operational_impact_snapshots_tenant_date', 'operational_impact_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_inventory_risk_snapshots_tenant_date', 'inventory_risk_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    op.create_index('ix_export_links_token', 'export_links', ['token'], unique=True)
    op.create_index('ix_escalation_rule_tenant_type', 'escalation_rules', ['tenant_id', 'alert_type'], unique=False)
    op.create_index('ix_email_delivery_log_tenant_status', 'email_delivery_log', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_custom_segments_tenant_id', 'custom_segments', ['tenant_id'], unique=False)
    op.create_index('ix_cost_inputs_tenant_type', 'cost_inputs', ['tenant_id', 'input_type'], unique=False)
    op.create_index('ix_cost_input_versions_cost_input_id', 'cost_input_versions', ['cost_input_id', 'version_number'], unique=False)
    op.create_index('ix_cohort_snapshots_window', 'cohort_snapshots', ['observation_window_days'], unique=False)
    op.create_index('ix_cohort_snapshots_tenant', 'cohort_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_cohort_snapshots_cohort_dates', 'cohort_snapshots', ['cohort_start_date', 'cohort_end_date'], unique=False)
    op.alter_column('cohort_snapshots', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cohort_snapshots', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_annotations_tenant_id', 'annotations', ['tenant_id'], unique=False)
    op.create_index('ix_annotations_saved_view_id', 'annotations', ['saved_view_id'], unique=False)
    op.create_index('ix_annotations_event_date', 'annotations', ['event_date'], unique=False)
    op.create_index('ix_annotations_created_by_id', 'annotations', ['created_by_id'], unique=False)
    op.create_index('ix_analysis_view_shares_tenant_id', 'analysis_view_shares', ['tenant_id'], unique=False)
    op.create_index('ix_analysis_view_shares_shared_by_id', 'analysis_view_shares', ['shared_by_id'], unique=False)
    op.create_index('ix_analysis_view_shares_saved_view_id', 'analysis_view_shares', ['saved_view_id'], unique=False)
    op.create_index('ix_alert_thresholds_tenant_id', 'alert_thresholds', ['tenant_id'], unique=False)
    op.create_index('ix_alert_recipients_user_id', 'alert_recipients', ['user_id'], unique=False)
    op.create_index('ix_alert_recipients_tenant_id', 'alert_recipients', ['tenant_id'], unique=False)
    op.create_index('ix_alert_event_log_tenant_created', 'alert_event_log', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_alert_event_log_tenant_alert', 'alert_event_log', ['tenant_id', 'alert_id'], unique=False)
    op.create_index('ix_alert_dismiss_tenant_user', 'alert_dismissals', ['tenant_id', 'user_id'], unique=False)
    op.create_index('ix_alert_dismiss_tenant_alert', 'alert_dismissals', ['tenant_id', 'alert_id'], unique=False)
    op.create_index('ix_alert_ack_tenant_user', 'alert_acknowledgements', ['tenant_id', 'user_id'], unique=False)
    op.create_index('ix_alert_ack_tenant_alert', 'alert_acknowledgements', ['tenant_id', 'alert_id'], unique=False)
    op.drop_constraint(None, 'acquisition_cohorts', type_='foreignkey')
    op.create_foreign_key('acquisition_cohorts_tenant_id_fkey', 'acquisition_cohorts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_acquisition_cohorts_tenant', 'acquisition_cohorts', ['tenant_id'], unique=False)
    op.create_index('ix_acquisition_cohorts_cohort_dates', 'acquisition_cohorts', ['cohort_start_date', 'cohort_end_date'], unique=False)
    op.create_table('klaviyo_campaigns',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connector_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('external_campaign_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('campaign_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('recipients', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='klaviyo_campaigns_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='klaviyo_campaigns_pkey')
    )
    op.create_index('ix_klaviyo_campaigns_tenant_id', 'klaviyo_campaigns', ['tenant_id'], unique=False)
    op.create_index('ix_klaviyo_campaigns_sent_at', 'klaviyo_campaigns', ['sent_at'], unique=False)
    op.create_table('shopify_refunds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('connector_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('external_refund_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('external_order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refund_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector_integrations.id'], name='shopify_refunds_connector_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['shopify_orders.id'], name='shopify_refunds_order_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='shopify_refunds_tenant_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shopify_refunds_pkey'),
    sa.UniqueConstraint('tenant_id', 'connector_id', 'external_refund_id', name='uq_shopify_refund_per_connector')
    )
    op.create_index('ix_shopify_refunds_tenant_id', 'shopify_refunds', ['tenant_id'], unique=False)
    op.create_index('ix_shopify_refunds_refund_created_at', 'shopify_refunds', ['refund_created_at'], unique=False)
    op.create_index('ix_shopify_refunds_order_id', 'shopify_refunds', ['order_id'], unique=False)
    op.create_index('ix_shopify_refunds_connector_id', 'shopify_refunds', ['connector_id'], unique=False)
    # ### end Alembic commands ###
